### ISSUE TITLE
PNG files missing from Imgur

### ISSUE THREAD

**Issue by RichShillingtonMSFT** [DevGonzi/uMod-InfoPanel#3]
Seems like the image files referenced in you .cs file are all missing from http://i.imgur.com.

**Comment by jamespero** [comment]
Looks like there's more issues with the images than just that. I've tried modifying the plugin's urls directly and they still don't take. I'm going to look into it and if I can get it working with any images I'll created a pull request. Not sure it will be pulled in or not as it seems this plugin is dead in terms of support.
